project:
  type: website
  output-dir: docs

execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website:
  page-navigation: true
  page-footer: 
    center: "NASA and NEON Airborne Hyperspectral Workshop - ESA 2025"

  title: "NEON AOP & NASA AVIRIS Airborne and Field Data Workshop"
  site-url: https://NEONScience.github.io/neon-nasa-hsi-workshop/
  repo-url: https://github.com/nasa/neon-nasa-hsi-workshop/

  sidebar:
    title: "NEON AOP & NASA AVIRIS Airborne Hyperspectral Data Workshop"
    logo: img/ornl_daac_neon_combined_logo.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://NEONScience.github.io/neon-nasa-hsi-workshop/
        text: "NEON NASA Hyperspectral Workshop Website"
      - icon: github
        href: https://github.com/NEONScience/neon-nasa-hsi-workshop
        text: "NEON NASA Repository"
        
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - section: "Welcome"
        contents:
        - text: "2025 ESA Workshop"
          href: index.qmd
        - text: "Repository Description"
          href: neon-nasa.qmd
      - section: "Setup Instructions"
        contents:
        - text: "Prerequisites"
          href: setup/prerequisites.md
        - text: "Cloud Workspace Setup"
          href: setup/workshop_setup.qmd
        - text: "Local Python Environment Setup"
          href: setup/setup_instructions.md
      - section: "Background"            
        contents: 
          - text: "NEON Airborne Data Background"
            href:  background/neon_background.qmd
          - text: "NASA Airborne Data Background"
            href:  background/nasa_airborne_background.qmd
          - text: "Comparing NEON and NASA Airborne Campaigns"
            href:  background/nasa_neon_comparison.qmd
      - section: "Tutorials"            
        contents: 
          - text: "1 NEON - Reflectance Visualization and Classification"
            href: neon/01_neon-refl-classification.ipynb
      - section: "Contributing"
        contents:
          - href: CONTRIBUTING.md
          - href: CODE_OF_CONDUCT.md
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo,theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
