---
title: "Plot to Plane: Working with NASA and NEON Airborne and Field Datasets"
---


NASA’s airborne science program and the NSF-funded National Ecological Observatory Network's (NEON's) Airborne Observation Platform (AOP) offer complementary remote sensing datasets ideal for carrying out large-scale ecological research. Both facilities operate similar airborne imaging spectrometers to collect visible to shortwave infrared (VSWIR) hyperspectral data, supporting regional ecosystem studies.

The Oak Ridge National Laboratory Distributed Active Archive Center (ORNL DAAC) archives data from NASA-funded ecological campaigns focusing on diverse environments such as river deltas and wetlands, the arctic, and tropics across multiple continents (North and Central America, South Africa). NEON's AOP gathers high-resolution hyperspectral imagery, lidar, and RGB photography at 81 U.S. sites, offering repeat data spanning 2-10 years, with collections starting in 2013.

This workshop introduces NEON and NASA airborne and field datasets through live-coding exercises presented as Python Jupyter Notebook tutorials, demonstrating data access, exploration, and analysis. Participants will learn to apply these datasets to answer ecological research questions, gaining insights into regional and landscape areas of interest. 

This workshop is hosted by [National Ecological Observatory Network (NEON)](https://neonscience.org/), NASA [Land Processes Distributed Activate Archive Center(LP DAAC)](https://lpdaac.usgs.gov/) and [NASA Jet Propulsion Laboratory (JPL)](https://www.jpl.nasa.gov/) with support from the NASA [Openscapes](https://nasa-openscapes.github.io/) project.  
Hands-on exercises will be executed from a [Jupyter Hub on the Openscapes 2i2c cloud instance](https://workshop.openscapes.2i2c.cloud/).

<iframe src="https://docs.google.com/presentation/d/1XrdG9P5rLNR8C1TeLpf80YZUCtqdmUev/embed?start=false&loop=false&delayms=3000" frameborder="0" width="750" height="445" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Agenda

| Time | Description | Leads/Instructors |  
|------|---------------------|-------------| 
|8:00 AM|Introduction and Overview of NEON and NASA Airborne and Field Data|Bridget Hass and Michele Thornton|  
|8:05 AM|Overview of NEON Airborne Observation Platform|Bridget Hass|  
|8:30 AM|Notebook 1: Working with NEON Hyperspectral Data|Bridget Hass|
|9:00 AM|Notebook 2: Pairing NEON and Field Hyperspectral Data|Bridget Hass|
|9:30 AM|Break||
|9:35 AM|Overview of NASA AVIRIS Missions|Michele Thornton|  
|10:00 AM|Notebook 3: Exploring SHIFT Data|Michele Thornton| 
|10:55 AM|Discussion and Wrap Up|All|


## Contact Info  

Email: <LPDAAC@usgs.gov>  
Voice: +1-866-573-3222  
Organization: Land Processes Distributed Active Archive Center (LP DAAC)¹  
Website: <https://lpdaac.usgs.gov/>  
Date last modified: 05-21-2024

¹Work performed under USGS contract 140G0121D0001 for NASA contract NNG14HH33I.
