---
title: "NEON and NASA Airborne and Field Tutorials"
---

> Please view the [NEON NASA Workshop Page](https://NEONScience.github.io/neon-nasa-hsi-workshop/) for workshop details. **Resources in this repository have been developed using the Openscapes 2i2c JupyterHub cloud workspace.**

Welcome to the **NEON - NASA Airborne Hyperspectral Data Resources** Repository! This repository provides Python Jupyter notebooks to help the community work with visible to short-wave infrared (VSWIR) imaging spectroscopy data from NEON's Airborne Observation Platform and missions carried out with the NASA AVIRIS sensors. These complimentary hyperspectral datasets provide an opportunity to conduct ecological research at large scales, and also can be paired with complimentary satellite datasets such as the EMIT (Earth Surface Mineral Dust Source Investigation) and future SBG (Surface Biology and Geology) VSWIR sensor.

In the interest of open science, this repository has been made public, but is still under active development. Contributions from all parties are welcome.

---

## Contact Info  

### NEON AOP


|||
|-----------|-------------|
|Organization|National Ecological Observatory Network Airborne Observation Platform (NEON AOP)^1^||
|Website|<https://neonscience.org/>|  
|Contact|<https://www.neonscience.org/about/contact-us/>|   

^1^NEON is a project fully funded by the National Science Foundation and operated by Battelle.


### ORNL DAAC

|||
|-----------|-------------|
|Organization|NASA Earthdata Data Center, Oak Ridge National Laboratory Distributed Active Archive Center (ORNL DAAC)|
|Website|<https://www.earthdata.nasa.gov/centers/ornl-daac>|  
|Contact|NASA Earthdata Forum: <https://forum.earthdata.nasa.gov/>|